config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/gogogo', to: 'pages#create_xmls', as: 'gogogo'
  get '/check_ingredients_and_emissions', to: 'pages#check_ingredients_and_emissions', as: 'check_datas'
  get '/add_annual_sales', to: 'pages#add_annual_sales', as: 'add_annual_sales'
  get '/destroy_feedback', to: 'pages#destroy_feedback', as: 'destroy_feedback'
  post '/add_countries', to: 'pages#add_countries', as: 'add_countries'
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => "/cable"
end

app/models/annual_sale.rb
class AnnualSale < ApplicationRecord
  def self.xml_files_list_with_extension
    pluck(:file_id).uniq.map{ |file_id| file_id + ".xml" }
  end
  def self.xml_file_ids_list
    pluck(:file_id).uniq
  end
end

app/models/annual_sales_update_feedback.rb
class AnnualSalesUpdateFeedback < ApplicationRecord
  serialize :missing_on_ftp, Array
  serialize :absent_in_csv, Array
  serialize :missing_countries, Hash
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :product

  validates :product_id, uniqueness: { scope: :code }
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :product

  validates :product_id, uniqueness: true

  serialize :datas, Hash
end

app/models/emission.rb
class Emission < ApplicationRecord
  belongs_to :product

  validates :product_id, uniqueness: { scope: :cas }
end

app/models/emission_location.rb
class EmissionLocation < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :product

  validates :product_id, uniqueness: { scope: :cas }

  serialize :datas, Hash
end

app/models/ingredient_location.rb
class IngredientLocation < ApplicationRecord
end

app/models/missing_xml.rb
class MissingXml < ApplicationRecord
  serialize :elements, Array
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  belongs_to :product

  validates :product_id, uniqueness: true

  serialize :datas, Hash
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :countries, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :emissions, dependent: :destroy
  has_one :presentation, dependent: :destroy
  has_one :design, dependent: :destroy

  serialize :datas, Hash
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    missing_ingredient_xml = MissingXml.find_by(xml_type: "ingredient")
    @missing_ingredient_cas = missing_ingredient_xml.elements if missing_ingredient_xml
    missing_emission_xml = MissingXml.find_by(xml_type: "emission")
    @missing_emission_cas = missing_emission_xml.elements if missing_emission_xml
    @job_in_progress = Sidekiq::Workers.new.size > 0
    @feedback = AnnualSalesUpdateFeedback.last
  end
  def check_ingredients_and_emissions
    CheckIngredientsAndEmissionsJob.perform_later
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js
    end
  end
  def create_xmls
    CheckDatasAndCreateXmlsJob.perform_later #.set(queue: :critical).perform_later
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js
    end
  end
  def add_annual_sales
    AddAnnualSalesDatasJob.perform_later #.set(queue: :critical).perform_later
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js
    end
  end
  def add_countries
    codes = params[:country_codes][:codes].upcase.gsub(/\s/, "").split(",")
    AddCountriesToXmlsJob.perform_later(countries: codes)
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js
    end
  end
  def destroy_feedback
    AnnualSalesUpdateFeedback.destroy_all
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EuXmlGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container my-container">
      <%= render "shared/flashes" %>
      <div class="min-full-height <%= "flexline" if params[:controller].match("devise") %>">
        <%= yield %>
      </div>
      <div id="footer" class="text-center">
        Made with <i class="fas fa-heart"></i> by Thomas Desmoulins
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/_add_countries_form.html.erb
<%= simple_form_for :country_codes, url: add_countries_path, remote: true do |f| %>
  <%= f.input :codes, label: "Lister les codes pays des pays à ajouter (séparés par des virgules) :", placeholder: "FR,DE,ES,IT" %>
  <%= f.submit "Lancer l'ajout des pays", class: "c2a" %>
<% end %>

app/views/pages/_annual_sales_feedback.html.erb
<div id="missing_on_ftp" class="<%= "hidden" if feedback && feedback.missing_on_ftp.empty? %>">
  Les file_ids suivants, présents dans le CSV, n'ont pas été trouvés sur le FTP :
  <ul>
    <% if feedback %>
      <% feedback.missing_on_ftp.each do |file_id| %>
        <li><%= file_id %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<div id="absent_in_csv" class="<%= "hidden" if feedback && feedback.absent_in_csv.empty? %>">
  Les file_ids suivants, présents sur le FTP, n'ont pas été trouvés dans le CSV :
  <ul>
    <% if feedback %>
      <% feedback.absent_in_csv.each do |file_id| %>
        <li><%= file_id %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<div id="missing_countries" class="<%= "hidden" if feedback && feedback.missing_countries.empty? %>">
  Les blocs 'Presentation' suivants n'ont pas été trouvés dans les fichiers source :
  <ul>
    <% if feedback %>
      <% feedback.missing_countries.each do |file, countries| %>
        <li><%= file %> : <%= countries.join(", ") %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<%= link_to "ok, supprimer le message", destroy_feedback_path, remote: true %>

app/views/pages/_missing_xmls.html.erb
Les ingredients suivants, présents dans le csv, n'ont pas été trouvés dans les xml_sources :
<ul id="missing-ingredients">
  <% missing_ingredients.each do |cas| %>
    <li><%= cas %></li>
  <% end %>
</ul>
Les emissions suivants, présents dans le csv, n'ont pas été trouvés dans les xml_sources :
<ul id="missing-emissions">
  <% missing_emissions.each do |cas| %>
    <li><%= cas %></li>
  <% end %>
</ul>

app/views/pages/add_countries.js.erb
function refreshPage(){
  const addCountriesCont = document.getElementById("add_countries_container");
  addCountriesCont.innerHTML = "<%= j render 'pages/add_countries_form' %>"
}

refreshPage();

app/views/pages/destroy_feedback.js.erb
var annualSalesFeedback = document.getElementById("add-sales-feedback");
annualSalesFeedback.classList.add("hidden");

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success text-center" role="alert">
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning text-center" role="alert">
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <%= alert %>
  </div>
<% end %>